### ISSUE TITLE
Data Size Reduction

### ISSUE THREAD

**Issue by san89** [MLblog/jads_kaggle#73]
To investigate and implement different methods to reduce the image size.

Responsables: @ystoyanov ,  @Christiannewisse , Dmytro, @palindrome6

**Comment by Christiannewisse** [comment]
As well image classification as data size reduction are totally new to me. However, I tried to make a list of techniques/options that might be interesting to reduce data size (the curse of dimensionality): 
Options to reduce data size (curse of dimensionality):

- Change to only one channel 
- Principal component analysis (PCA) 
         Decompose a multivariate data set in a set of components that explain a maximum amount of the variance.
        Linear, unsupervised method
- Linear Discriminant Analysis (LDA)
        Besides the components that maximize the variance of the data, we are additionally interested in the axes that maximize the separation between multiple classes.
       Linear, supervised method
- t-Distributed Stochastic Neighbour Embedding (t-SNE)
         Aims to convert the Euclidean distances between points into conditional probabilities. A Student-t distribution is then applied on these probabilities which serve as metrics to calculate the similarity between data points.
        Non-linear, probabilistic dimensionality method 

Feel free to comment on these methods or to add more! Besides that, I think we can use this channel to report on which techniques/methods we are working (so that we do not work on the same techniques/methods).

**Comment by san89** [comment]
No followup on this issue.
